const story = {
  SLO: {
    contents: [
      'Živjo! Če te zanima dolgočasna zgodba mojega življenja, predstavljena na kolikor sem zmožen zanimiv način, si na pravem mestu. Če te zanima dolgočasna zgodba mojega življenja podana na kar se da dolgočasen, ampak učinkovit način pa klikni sem.',

      'Torej . . . Kje se je začelo?',

      'Ko sem bil mali skuštranec, nekaj let star, sem na zasnežen poznonovembski dan v izložbi pred Sparom videl nekaj neverjetno vznemirljivega. Videl sem rumene robotke iz legic.\n To je bil set s programirljivo enoto. Domišljija mi je nemudoma prevzela vse vizualne kapacitete. Videl sem že kako bom naredil svojega robota, svoj avto, potoval na druge planete, rešil svet pred invazijo modrih nezemljanov. Neskončno možnosti. \n\nBližal se je že Miklavž in seveda sem dodal te legice kot edino stvar na svoj seznam želj. Šah mat, Miklavž. In tako se je začelo.',

      'Več let kasneje, polnih hroščkastih robotkov iz legic, polnih elektronskih setov za otroke, polnih naskrivaj razstavljenih in nespretno za silo nazaj sestavljenih radijev, televizij in ostale tehnike, ki so si je starši želeli delujoče, se je pri uri likovne vzgoje na mojem super kul MP4 playerju znašel komad od U2 - Beautiful Day. Naježile so se mi kocine na rokah. To je to. To je glasba, ki premika gore. Takrat sem začutil, da bom roker (ja, ta komad se mi je zdel skoraj kot hard rock). Poprijel sem za materino kitaro in iz nje vsak dan izvabljal neposlušljiv hrup. Prsti so postali spretnejši, možgančki hitrejši, budget pa je ostal blizu nič. Vsaķič, ko nekaj hočem, se bogsigavedizakaj, probam to narediti sam. Ampak ojačevalce in efektov še nisem znal. Kaj storiti? \n\nVpisal sem se na srednjo elektrotehniško, Vegovo. \n\nBil sem poln upanja, da bom po prvih dneh že štromarski genij. Kmalu sem spoznal, da temu ne bo tako.\n\nTam me niso naučili delati ojačevalcev in efektov. So me pa naučili spajkati, brati datasheete in osnovne koncepte. Ravno dovolj, da sem se lahko učenja lotil sam. Naredil sem 100 vatne ojačevalnike, ojačevalnike v piksnah od barve, škatlicah od bombonov, iz starih radijev, mini vgradljive ojačevalce, vglavnem cel kup ojačevalcev, pa sintesizerje, binarne ure, arduino shielde ... Ampak kaj pa roboti? Kaj pa vesoljske ladje? Procesorji? Ne tega pa nisem znal.',

      'Zdi se kot, da so me v življenju naključni nepovezani trenutki usmerjali na pot programiranja.\n\nTako je v četrtem letniku, je prfesor vprašal, če bi se kdo prijavil na tekmovanje v programirjanju mikrokrmilnikov. Pogledal sem levo, vsi so povešali pogled. Pogledal sem še desno in nazaj. Isto. Pogledal sem kolega na levi, in je nesigurno skomignil. Pa sva se javila. Z neverjetnimi izkušnjami ene dvajsetih vrstic v c-ju in in brez plana. Pa je šlo. Poprosil sem prijatelja z računalniške smeri, če bi mi razkril svet te čudežne obrti. Tako se je tisto popoldne za mizo v guinnessu moje življenje spremenilo. Pokazal mi je osnove c-ja, in že sem prižigal lučke, bral senzorje in knofke, pisal driverje za zaslončke in premikal tuljavice. S sošocem sva si naredila svojo plošcico s krmilnikom, si napisala knjižnjice, prešpricala vse možne ure sociologije in se odpravila na tekmovanje. Bila sva druga. Ali pa tretja. Ne vem, in ne da se mi iskati plakete. Vsekakor pa nama je precej uspelo. Začutil sem, da ja. Programiranje je to.',

      'Vseeno sem se vpisal na Eletrotehniško fakulteto. Ne vem zakaj. Verjetno se mi je zdela edina logična poteza. Edini predmet, ki sem ga kdajkoli dobil 10 je bil programiranje 1, kjer smo imeli osnove web developmenta... to se mi zdi, da pove nekaj. \n\n Po prvem letniku, po praksi v kolektorju, mi je mentor predlagal, da naj pošljem prošnjo v Kolektor Idrium. To je bila precej kul skupina študentov, kjer smo izdelovali naprave, za notranjo uporabo. Večinoma so bili to zaganjalniki motorjev, merilne naprave, krmilniki za to in ono. Ampak kmalu sem se začel dolgočasiti. Rabil sem nekaj več. Svoje naprave sem rabil bolj ... žive.',

      'Potem pa je končno na vrsto prišel precej kul projekt, s super dogočasnim imenom: "Varilni izvor inverterski", sam sem ga poimenoval "RoboVarilc2000".      Šlo je za mašino s serijo pnevmatskih ventilov in dveh varilnih glav, ki so se prožili po sekvenci ki jo je nastavil uporabnik na touch panelu.      Avtomatizirana mašina, GUI, kako bi lahko ne prosil, če smem prevzeti ta projekt? Tresočega glasu sem rekel: "Jurko. A bi lahko tega jaz prevzel?". "Lahko," je rekel "Ampak zna biti veliko dela." Končno. Končno nekaj kul. Zakopal sem se. Nadobudno sem se lotil na tem krmilniku iz zgodnjih 2000 poustvariti Material design, ki je bil takrat all the rage, seveda more moja mašina lepo izgledati. Stvar mi je uspela. Robot? Ja. Kul? Ja. V prototipni delavnici še danes veselo piha in vari. Štorast video, ki se ga posnel kot dokaz delovanja pa je dostopen tu. ',

      'Takrat mi je končno dokončno kapnilo, da če hočem delati res kul stvari, je moja najboljša možnost programiranje. Tako sem nekaj mesecev kasneje nervozen  poslal prošnjo v Kolektor Vision, kjer se ukvarjajo z robotskim vidom za industrijo. Tam sem se učil procesiranja slik, razmišljanja, če sem res pomislil na vse edge case. Ugotovil sem da je Linux precej fajn, da mi je VIM všeč in da je C++ grozen za uporabo. Na faksu je tudi postajalo bolj zanimivo. Kjer se je le dalo sem izbiral projekte bolj softwarske narave, kot so barvanje črnobelih slik z nevronskimi mrežami, risanje VR grafov, segmentacijo elementov, kul stvari.',

      'Svojo študentsko službo sem v iskanju finančne neodvisnosti in denarja za vsaj občasno pijačo s kolegi zamenjal za programerja v videoprodukcijski hiši. Tu so mi pustili, da si sam izbiram tehnologije, ki jih bom uporabljal. Vedel sem že, da se hočem lotiti bolj web tehnologij, da hočem imeti več opravka z grafičnimi vmesniki, in da hočem, da se moji programčki pogovarjajo in delujejo v harmoniji med sabo in z ostalim svetom. Tu sem napisal svoje prve frontende v Reactu, svoje prve serverčke v Nodu, avtomatiziral snemanje precej produkcij, napisal in uporabljal APIje, releasal prve internetne strani in ogromno drugih drobnarij. Sedaj lahko moje pridne delavce najdete živeče polno integrirane v praktično vseh VPK produkcijah.',

      'Sedaj pa si želim naprej. In naprej ne morem sam. Okoli sebe rabim druge ustvarjalce, druge ljudi, ki konceptom podarjajo življenja in smisel, od katerih lahko pobiram dobre prakse, učinkovite pristope, izkušnje in znanje. Nekaj časa je to šlo z branjem knjig in člankov predlaganih na hacker news, sedaj pa se mi zdi da se je moj napredek resno upočasnil, in nisem take vrste človek, ki bi lahko to mirno gledal, brez da bi poskušal kaj spremeniti. Nočem se preprosto zabubiti v udobje nerazburljivega vsakdana in mirno čakati na konec. Vse kar lahko ponudim v zameno je ogromno entuziazma, večji del svojega življenja in svoje omejene izkušnje. Kaj praviš? Bi lahko bil del naslednjega poglavja?'
    ],
    titles: [
      'KLEMEN the origin',
      'poglavje I - Iskra preskoči',
      'poglavje II - Roker po vegovsko',
      'poglavje III - Brca v pravo smer',
      'poglavje IV - Štrom se vrača',
      'poglavje V - Uspelo mi je. Živ je. MVAHAHAH',
      'poglavje VI - Franken ekspert',
      'poglavje VII - S trebuhom za kruhom',
      'poglavje VIII - Tu prideš na vrsto ti, bralec'
    ]
  }
}
 export default story
